### PR TITLE
Clicking bounding boxes highlights the corresponding mei line.

### PR DESCRIPTION
**Pull request by napulen**
- Reimplementing `highlightClickHandler()` to fit `diva.js` v5 and highlight the corresponding mei lines
- Adjusting to the naming convention of the IIIF json data in the `resources/mei` folder

### CODE REVIEW

**Review by vigliensoni — COMMENTED** [review]
The MEI files were within a folder named by the manuscript name in case we have more manuscripts. With this approach, you will need all the files in the same folder.

In the end, we know that the files may be fetch using IIIF manifests, but if we want different manuscripts to showcase different manuscripts, it might be useful to have them in different folders.

**Comment by napulen** [comment]
Question: Are the mei files we are going to use always going to be stored and controlled by ourselves, or are we fetching those from third-parties? If the answer is the latter, I would invest the time in seeing how third-parties store and serve the mei files instead of writing another layer of ajax requests for subfolders in this repository. If the answer is the first one, then I agree, subfolders per manuscript are better, I am going to include that in the next pull request.

**Comment by vigliensoni** [comment]
Although the answer is the latter for the general use of the app, I think
the former may be useful to demo the app.

**Comment by napulen** [comment]
Alright. I am re-opening the PR once I implement the ajax requests for fetching the subfolders.

**Pull request closed without merging**
